<?php include "cities.php"; ?>
<div id="header">

        <h2 class="title"><a href="#">Vihko</a></h2>


        <ul class="navigation">
                <li>Laitteet</li>
                <li>Varaus</li>
                <li>Yhteenveto</li>
        </ul>
</div>
<div id="left-column">
	<h3>Valitse tuote:</h3>
	<p class="info">Laiteet on j&auml;rjestetty sijainnin mukaisesti. Pyri aina varaamaan laite joka on mahdollisimman l&auml;hell&auml; tapahtumapaikkaa.</p>
	<div class="styled-select">
            <?php  
            echo $this->form()->openTag($laitteetform);
            echo $this->formRow($laitteetform->get('laitteet'));
            echo $this->form()->closeTag();?>
	</div>
	<p class="info">Valittuasi laitteen p&auml;&auml;set katsomaan ko laitteen varaustilannetta kalenterista ja varaamaan laitteen tapahtumaasi.</p>


	<h3 id="muokkaa" onClick="showdivi('muokkaakohdeDivi');" style="cursor:pointer; display:none;">Muokkaa kohdetta:</h3>
		<div id="muokkaakohdeDivi" style="display:none;">
		<div class="poistabutton"><a onClick="tarkistakohteenpoisto();" href="#" title="poistava varaus">Poista kohde</a></div>
		<form method="post" action="">
			<input type="text" id="nimi" name="nimi" class="tuotteennimi" value="" required="required">
			<div class="styled-select">
			<select id="muokkaapaikka" name="paikka">
			<option value='-'>Tuotteen paikka</option>";
			<option value='Helsinki'>Helsinki</option>";
			<option value='Oulu'>Oulu</option>";
			<option value='Jyväskylä'>Jyväskylä</option>";
			</select>
			</div>
			<textarea id="lisatietoja" name="lisatietoja" value=""></textarea>
			<input type="hidden" id="formtype" name="formtype" value="muokkaa">
			<input type="hidden" id="id_item" name="id_item" value="">
			<p>Valitse normaalikuljetuskaupungit.</p>
			<div class="styled-select">
			
			<select id="laitteet" name="laitteet" onChange="lisaaKaupunki(this,'muokkaa')">
			<option value='-'>-</option>";
			<?php
			
			sort($cities);
			foreach($cities as $key => $item){

				echo "<option value='".$item."'>".$item."</option>";
			}
			?>
			</select>
			</div>
			<input type="hidden" name="muokkaakaupungit" id="muokkaakaupungit" value="">
			<div id="muokkaakaupungit_show"></div>
			
			
			<input type="Submit" value="Muokkaa" name="muokkaa" style="cursor:pointer;">
		</form>
		<?php if(isset($sucess)){?>
		<div class="sucess">
			<img src="<?php bloginfo('template_url'); ?>/assets/sucess.jpg">
		</div>
		<?php } ?>
		</div><!--omattiedot-->
	<h3 id="lisaa" onClick="showdivi('lisaakohdeDivi');" style="cursor:pointer">Lis&auml;&auml; tuote:</h3>
		<div id="lisaakohdeDivi" style="display:none;">
		<form method="post" action="">
			<input type="text" id="nimi" name="nimi" class="tuotteennimi" placeholder="Lisää uusi kohde" required="required">
			<div class="styled-select">
			<select id="paikka" name="paikka">
			<option value='-'>Tuotteen paikka</option>";
			<option value='Helsinki'>Helsinki</option>";
			<option value='Oulu'>Oulu</option>";
			<option value='Jyväskylä'>Jyväskylä</option>";
			</select>
			</div>
			<textarea placeholder="Lisätiedot" id="lisatietoja" name="lisatietoja"></textarea>
			<input type="hidden" id="formtype" name="formtype" value="lisaa">
			<p>Valitse normaalikuljetuskaupungit.</p>
			<div class="styled-select">
			<select id="laitteet" name="laitteet" onChange="lisaaKaupunki(this,'')">
			<option value='-'>-</option>";
			<?php
			sort($cities);
			foreach($cities as $key => $item){

				echo "<option value='".$item."'>".$item."</option>";
			}
			?>
			</select>
			</div>
			<input type="hidden" name="kaupungit" id="kaupungit" value="">
			<div id="kaupungit_show"></div>
			<input type="Submit" value="Lisää" name="add" style="cursor:pointer;">
		</form>

		</div>

	<div id="paivienvalinta" style="display:none;">
	<div class="kohde">
		<h4>Valittu tuote: </h4>
		<p id="laitteennimi"></p>
		<h4>Lisätiedot: </h4>
		<p id="laitteenlisatieto"><p>
		<h4>Laitteen kuljetus: </h4>
		<p id="normaali_kuljetus"><p>
	
	<h2 name="" id="valitutpaivat"></h2><br>


	<input type="hidden" name="selecteddate" id="selecteddate" value="">
	<div id="varauksenhinta"></div>
	</div>
	</div>

</div>

<div id="right-column">
	<div id="laitelista"></div>
	<p style="float:left; display:none;" class="nonlink_link" id="varaustietolinkki" onClick="haeMenneetvaraukset('','expd',0);">Katso varaushistoria</p>
	<?php include "main.phtml";?>
	
	<div id="laitteenkalenteri"></div>
</div>
	

<div id="pagination" class="pagination" style="display:none;">

<div class="alignleft">
<a href="#"
  title="">

<div class="alignright">
<a href="#" 
 title="">Seuraava sivu</a>

</div>

</div><!-- .navigation -->